### ISSUE TITLE
run_colorsExample 

### ISSUE THREAD

**Issue by JCirera** [fcomitani/simpsom#3] opened 2019-02-18 16:36 UTC
Figures 2 and 3 of the .run_colorsExample() do not appear. I also tried to use the .project function with another dataset and the result was the same. I am using python 3.6.5 64b, numpy=1.14.3,  matplotlib=2.2.2,  sklearn=0.20.1 and no errors appear neither. Anyone know what to do?

**Comment by fcomitani** [comment] 2019-02-25 21:04
Hello @JCirera,

I couldn't reproduce your problem, is anything at all printed to screen when you run those functions?

Could you try installing the latest version directly from github instead of the one available on pip? I just added the option to explicitly specify the path where to save files and graphs, by default it saves everything in the directory where you are running the script. 

Could you try saving them to a different directory than the default one and let me know how that goes?
e.g. run_colorsExample("/home/username/test_folder/")

**Comment by fcomitani** [comment] 2019-04-02 13:34
There was no follow up, so I am closing this issue.

**Closed as completed by fcomitani** 2019-04-02 13:34 UTC
Labels: wontfix
